import {
  FolderKanban,
  CheckCircle2,
  MapPin,
  HardHat,
  Users,
  UserCheck,
  Briefcase,
  ClipboardList,
  CalendarCheck,
  Package,
  AlertTriangle,
  XCircle,
  ShoppingCart,
  Hourglass,
  Warehouse,
  Wallet,
  Receipt,
  Banknote,
  AlertCircle,
  PiggyBank,
} from 'lucide-react';
import { formatCompactCurrency, formatNumber } from './format';

/**
 * Every KPI on the Reports dashboard, in display order. Each entry names the
 * `reportDefs` id its drill-down opens and the initial filters to apply, so
 * clicking a KPI always lands on the exact underlying records that KPI
 * summarises — never a generic unfiltered table.
 *
 * `pick(kpis)` reads the raw dashboard kpis object and returns the display
 * value, or `undefined` if this card should not render at all (the caller's
 * role/permissions never computed this figure server-side — see
 * reportService.getDashboard).
 */
export const KPI_DEFS = [
  {
    key: 'totalProjects',
    label: 'Total projects',
    icon: FolderKanban,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.totalProjects,
    format: formatNumber,
    reportId: 'projects',
    filters: {},
  },
  {
    key: 'activeProjects',
    label: 'Active projects',
    icon: FolderKanban,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.activeProjects,
    format: formatNumber,
    reportId: 'projects',
    filters: { status: 'active' },
  },
  {
    key: 'completedProjects',
    label: 'Completed projects',
    icon: CheckCircle2,
    tone: 'text-emerald-700 bg-emerald-50',
    pick: (k) => k.completedProjects,
    format: formatNumber,
    reportId: 'projects',
    filters: { status: 'completed' },
  },
  {
    key: 'totalSites',
    label: 'Total sites',
    icon: MapPin,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.totalSites,
    format: formatNumber,
    reportId: 'sites',
    filters: {},
  },
  {
    key: 'totalContractors',
    label: 'Total contractors',
    icon: HardHat,
    tone: 'text-amber-700 bg-amber-50',
    pick: (k) => k.totalContractors,
    format: formatNumber,
    reportId: 'contractors',
    filters: {},
  },
  {
    key: 'activeContractors',
    label: 'Active contractors',
    icon: HardHat,
    tone: 'text-amber-700 bg-amber-50',
    pick: (k) => k.activeContractors,
    format: formatNumber,
    reportId: 'contractors',
    filters: { status: 'active' },
  },
  {
    key: 'totalEmployees',
    label: 'Total employees',
    icon: Users,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.totalEmployees,
    format: formatNumber,
    reportId: 'employees',
    filters: {},
  },
  {
    key: 'activeEmployees',
    label: 'Active employees',
    icon: UserCheck,
    tone: 'text-emerald-700 bg-emerald-50',
    pick: (k) => k.activeEmployees,
    format: formatNumber,
    reportId: 'employees',
    filters: { status: 'active' },
  },
  {
    key: 'companyLabour',
    label: 'Company labour',
    icon: Briefcase,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.companyLabour,
    format: formatNumber,
    reportId: 'labourAssignments',
    filters: { labourType: 'company' },
  },
  {
    key: 'contractorLabour',
    label: 'Contractor labour',
    icon: HardHat,
    tone: 'text-amber-700 bg-amber-50',
    pick: (k) => k.contractorLabour,
    format: formatNumber,
    reportId: 'labourAssignments',
    filters: { labourType: 'contractor' },
  },
  {
    key: 'totalWorkforce',
    label: 'Total workforce',
    icon: Users,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.totalWorkforce,
    format: formatNumber,
    reportId: 'labourAssignments',
    filters: {},
  },
  {
    key: 'pendingLabourRequests',
    label: 'Pending labour requests',
    icon: ClipboardList,
    tone: 'text-amber-700 bg-amber-50',
    pick: (k) => k.pendingLabourRequests,
    format: formatNumber,
    reportId: 'labourRequests',
    filters: { status: 'SUBMITTED' },
  },
  {
    key: 'attendanceToday',
    label: "Attendance today",
    icon: CalendarCheck,
    tone: 'text-emerald-700 bg-emerald-50',
    pick: (k) => k.attendanceToday,
    format: (v) => formatNumber(v?.total ?? 0),
    hint: (v) => (v ? `${formatNumber(v.present || 0)} present · ${formatNumber(v.absent || 0)} absent` : undefined),
    reportId: 'attendance',
    filters: {},
  },
  {
    key: 'materialStockValue',
    label: 'Material stock value',
    icon: Package,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.materialStockValue,
    format: formatCompactCurrency,
    reportId: 'materials',
    filters: {},
  },
  {
    key: 'lowStockMaterials',
    label: 'Low stock materials',
    icon: AlertTriangle,
    tone: 'text-amber-700 bg-amber-50',
    pick: (k) => k.lowStockMaterials,
    format: formatNumber,
    reportId: 'materials',
    filters: { stockStatus: 'low' },
  },
  {
    key: 'outOfStockMaterials',
    label: 'Out of stock materials',
    icon: XCircle,
    tone: 'text-danger bg-danger-soft',
    pick: (k) => k.outOfStockMaterials,
    format: formatNumber,
    reportId: 'materials',
    filters: { stockStatus: 'out' },
  },
  {
    key: 'procurementRequests',
    label: 'Procurement requests',
    icon: ShoppingCart,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.procurementRequests,
    format: formatNumber,
    reportId: 'procurement',
    filters: {},
  },
  {
    key: 'pendingProcurement',
    label: 'Pending procurement',
    icon: Hourglass,
    tone: 'text-amber-700 bg-amber-50',
    pick: (k) => k.pendingProcurement,
    format: formatNumber,
    reportId: 'procurement',
    filters: { status: 'pending_approval' },
  },
  {
    key: 'warehouseStockQuantity',
    label: 'Warehouse stock quantity',
    icon: Warehouse,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.warehouseStockQuantity,
    format: formatNumber,
    reportId: 'warehouseStock',
    filters: {},
  },
  {
    key: 'warehouseStockValue',
    label: 'Warehouse stock value',
    icon: Wallet,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.warehouseStockValue,
    format: formatCompactCurrency,
    reportId: 'warehouseStock',
    filters: {},
  },
  {
    key: 'projectExpenses',
    label: 'Project expenses',
    icon: Receipt,
    tone: 'text-amber-700 bg-amber-50',
    pick: (k) => k.projectExpenses,
    format: formatCompactCurrency,
    reportId: 'expenses',
    filters: {},
  },
  {
    key: 'contractorPayments',
    label: 'Contractor payments',
    icon: Banknote,
    tone: 'text-emerald-700 bg-emerald-50',
    pick: (k) => k.contractorPayments,
    format: formatCompactCurrency,
    reportId: 'contractorPayments',
    filters: {},
  },
  {
    key: 'outstandingPayments',
    label: 'Outstanding payments',
    icon: AlertCircle,
    tone: 'text-danger bg-danger-soft',
    pick: (k) => k.outstandingPayments,
    format: formatCompactCurrency,
    reportId: 'contractorPayments',
    // The DB does not store 'outstanding' as a status value — outstanding is a
    // computed field (contract_value - paid_amount). Filtering by
    // payment_status='pending' is the closest approximation: pending records
    // are the ones that have not yet been settled (i.e., paid_amount < contract_value).
    filters: { status: 'pending' },
  },
  {
    key: 'remainingBudget',
    label: 'Remaining budget',
    icon: PiggyBank,
    tone: 'text-brand-600 bg-brand-50',
    pick: (k) => k.remainingBudget,
    format: formatCompactCurrency,
    reportId: 'projectFinancials',
    filters: {},
  },
];

/**
 * Two KPIs a CONTRACTOR should always be able to open even though the
 * dashboard summary never computes contractor-wide `totalContractors` /
 * `contractorPayments` figures for them (reportService.getDashboard only
 * fills those in for an org-wide viewer). A signed-in contractor still has
 * their own record and their own payment history — just reached through
 * these two report ids directly, with no KPI number attached.
 */
export const CONTRACTOR_SELF_REPORTS = [
  { reportId: 'contractors', label: 'My contractor record' },
  { reportId: 'contractorPayments', label: 'My payments' },
];
